public class opportunityClass {
    public static void oppList(){
        List<Opportunity> oppList = new List<Opportunity>();
        Opportunity opp1= new Opportunity(Name='ses',StageName='Qualification');
        Opportunity opp2= new Opportunity(Name='Messs');
        oppList.add(opp1);
         oppList.add(opp2);
        insert oppList;
    
        
        

        
        
        
    }

}